### ISSUE TITLE
Design doc review #1 - MVP List and Schema

### ISSUE THREAD

**Issue by aracpyon** [iamdanahn/RunWithMe#1]
**MVP**

- [x] It's a minor thing but change the dates from the finishing date to starting data
- [x] On Friday, you wouldn't have time working on any functional update. We spend the morning on updating your readme and then have the presentation time after lunch. Make sure to squeeze the feature you have on Friday before Friday. 
- [x] (User auth) Make sure to print error messages when user signs up/logs in with wrong information
- [x] (Add this to Making running routes MVP) Set up Google map api 
- [x] (Delete `CRUD` from the Comments MVP and add it to `Make running Routes`) Your CRUD functionality should be your `Making routes` MVP, not `Comments` MVP. User can create a route, read a route they created on `My Routes` page, edit it and delete it. 
- [x] Production README is on Friday (01/29/2021) 

**Schema**
- [x] (Users) Add birthday and gender columns to users as you need them for user's signup. 
- [x] (Users) Delete `Friends` and `routes` columns from the Users table
- [x] (Work out) You need a `workouts` table with `user_id` and `route_id`. On mapMyRun, you can search someone else's routes and add it as `log workout`. Try that see what columns you would need for it. Since this `workouts` table will record what routes the users have done before, so you wouldn't need a column `routes` on the users table. 
- [x] (Routes) Add `activity` column and this is going to be a dropdown
- [x]  (Routes) Consider to add `lat` and `lng` for each `start_pos` and `end_pos`. You might need more positions based on how users interact with the map. Start thinking and planning how you are going to draw line on the map with the google map API documents. The link is [here](https://developers.google.com/maps/documentation/javascript/overlays) 
- [x] (friending) this is a joinstable for user's friendship. Each row will show one `user_id` and one friend_id` at a time. `friends_id` should be `friend_id`.

**Comment by iamdanahn** [comment]
MVP
- It's a minor thing but change the dates from the finishing date to starting data
  - Idgi, could you explain what is wrong with the date?
- On Friday, you wouldn't have time working on any functional update. We spend the morning on updating your readme and then have the presentation time after lunch. Make sure to squeeze the feature you have on Friday before Friday.
  - Got it
- (User auth) Make sure to print error messages when user signs up/logs in with wrong information
  - Got it
- (Add this to Making running routes MVP) Set up Google map api
  - Got it (omg)
- (Delete CRUD from the Comments MVP and add it to Make running Routes) Your CRUD functionality should be your Making routes MVP, not Comments MVP. User can create a route, read a route they created on My Routes page, edit it and delete it.
  - Got it
- Production README is on Friday (01/29/2021)
  - Got it!

Schema

- (Users) Add birthday and gender columns to users as you need them for user's signup.
  - Got it 
- (Users) Delete Friends and routes columns from the Users table
  - Got it
- (Work out) You need a workouts table with user_id and route_id. On mapMyRun, you can search someone else's routes and add it as log workout. Try that see what columns you would need for it. Since this workouts table will record what routes the users have done before, so you wouldn't need a column routes on the users table.
  - Added
- (Routes) Add activity column and this is going to be a dropdown
  - Added 
- (Routes) Consider to add lat and lng for each start_pos and end_pos. You might need more positions based on how users interact with the map. Start thinking and planning how you are going to draw line on the map with the google map API documents. The link is here
  - Added and will review API docs 
- (friending) this is a joins table for user's friendship. Each row will show one user_id and one friend_id at a time. friends_id should be friend_id.
  - Got it

**Comment by aracpyon** [comment]
* It's a minor thing but change the dates from the finishing date to starting data 
=> Right now, your dates are on the finishing date. For example, Hosting on Heroku is on 19th, then User auth should be on 20th, not 21th.(And technically you will start on the user auth on the heroku day so you can even put it as 19th). Please update the dates accordingly. 
* On Friday, you wouldn't have time working on any functional update. We spend the morning on updating your readme and then have the presentation time after lunch. Make sure to squeeze the feature you have on Friday before Friday.
=> I unchecked out this because I don't see the dates updated and `Dashboard that tracks completed runs` is still on Jan 29th, which is Friday. It should be before Friday.

**Comment by iamdanahn** [comment]
Fixed all dates!

**Comment by aracpyon** [comment]
Looks good! Just fix Production Readme is on 29th!

**Comment by iamdanahn** [comment]
Done. 고맙s!
